# Generated by Django 6.0 on 2026-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(db_column='idperfil', primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(db_column='descripcionperfil', max_length=50)),
                ('perfilactivo', models.IntegerField(db_column='perfilactivo')),
                ('apellidos', models.CharField(db_column='apellidos', max_length=60)),
                ('nombres', models.CharField(db_column='nombres', max_length=60)),
                ('nacionalidad', models.CharField(db_column='nacionalidad', max_length=20)),
                ('lugarnacimiento', models.CharField(db_column='lugarnacimiento', max_length=60)),
                ('fechanacimiento', models.DateField(db_column='fechanacimiento')),
                ('numerocedula', models.CharField(db_column='numerocedula', max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'H'), ('M', 'M')], db_column='sexo', max_length=1)),
                ('estadocivil', models.CharField(db_column='estadocivil', max_length=50)),
                ('licenciaconducir', models.CharField(db_column='licenciaconducir', max_length=6)),
                ('telefonoconvencional', models.CharField(db_column='telefonoconvencional', max_length=15)),
                ('telefonofijo', models.CharField(db_column='telefonofijo', max_length=15)),
                ('direcciontrabajo', models.CharField(db_column='direcciontrabajo', max_length=50)),
                ('direcciondomiciliaria', models.CharField(db_column='direcciondomiciliaria', max_length=50)),
                ('sitioweb', models.CharField(db_column='sitioweb', max_length=60)),
            ],
            options={
                'db_table': 'DATOSPERSONALES',
            },
        ),
    ]
