# Generated by Django 6.0 on 2026-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_perfil_url',
            field=models.URLField(blank=True, db_column='foto_perfil_url', help_text='URL segura de la foto de perfil almacenada en Azure (PNG)', null=True),
        ),
    ]
