# Generated by Django 4.2.27 on 2026-01-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_datospersonales_foto_perfil_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(db_column='mostrar_cursos', default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia_laboral',
            field=models.BooleanField(db_column='mostrar_experiencia_laboral', default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.BooleanField(db_column='mostrar_productos_academicos', default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.BooleanField(db_column='mostrar_productos_laborales', default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.BooleanField(db_column='mostrar_reconocimientos', default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_venta_garage',
            field=models.BooleanField(db_column='mostrar_venta_garage', default=True),
        ),
    ]
