# Generated by Django 4.2.27 on 2026-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_datospersonales_mostrar_cursos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilidadSecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_experiencia_laboral', models.BooleanField(db_column='mostrar_experiencia_laboral', default=True)),
                ('mostrar_cursos', models.BooleanField(db_column='mostrar_cursos', default=True)),
                ('mostrar_reconocimientos', models.BooleanField(db_column='mostrar_reconocimientos', default=True)),
                ('mostrar_productos_academicos', models.BooleanField(db_column='mostrar_productos_academicos', default=True)),
                ('mostrar_productos_laborales', models.BooleanField(db_column='mostrar_productos_laborales', default=True)),
                ('mostrar_venta_garage', models.BooleanField(db_column='mostrar_venta_garage', default=True)),
            ],
            options={
                'db_table': 'VISIBILIDAD_SECCIONES',
            },
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_cursos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_experiencia_laboral',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_venta_garage',
        ),
    ]
