# Generated by Django 6.0 on 2026-01-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('idcursorealizado', models.AutoField(db_column='idcursorealizado', primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, db_column='nombrecurso', max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechainicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechafin', null=True)),
                ('totalhoras', models.IntegerField(blank=True, db_column='totalhoras', null=True)),
                ('descripcioncurso', models.CharField(blank=True, db_column='descripcioncurso', max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, db_column='entidadpatrocinadora', max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, db_column='nombrecontactoauspicia', max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, db_column='telefonocontactoauspicia', max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, db_column='emailempresapatrocinadora', max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('rutacertificado', models.CharField(blank=True, db_column='rutacertificado', max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'CURSOSREALIZADOS',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencilaboral', models.AutoField(db_column='idexperiencilaboral', primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(blank=True, db_column='cargodesempenado', max_length=100, null=True)),
                ('nombrempresa', models.CharField(blank=True, db_column='nombrempresa', max_length=50, null=True)),
                ('lugarempresa', models.CharField(blank=True, db_column='lugarempresa', max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, db_column='emailempresa', max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, db_column='sitiowebempresa', max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, db_column='nombrecontactoempresarial', max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, db_column='telefonocontactoempresarial', max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(blank=True, db_column='fechainiciogestion', null=True)),
                ('fechafingestion', models.DateField(blank=True, db_column='fechafingestion', null=True)),
                ('descripcionfunciones', models.CharField(blank=True, db_column='descripcionfunciones', max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('rutacertificado', models.CharField(blank=True, db_column='rutacertificado', max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'EXPERIENCIALABORAL',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('idproductoacademico', models.AutoField(db_column='idproductoacademico', primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(blank=True, db_column='nombrerecurso', max_length=100, null=True)),
                ('clasificador', models.CharField(blank=True, db_column='clasificador', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSACADEMICOS',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(db_column='idproductoslaborales', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, db_column='nombreproducto', max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, db_column='fechaproducto', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSLABORALES',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('idreconocimiento', models.AutoField(db_column='idreconocimiento', primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], db_column='tiporeconocimiento', max_length=100, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, db_column='fechareconocimiento', null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, db_column='descripcionreconocimiento', max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, db_column='entidadpatrocinadora', max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, db_column='nombrecontactoauspicia', max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, db_column='telefonocontactoauspicia', max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('rutacertificado', models.CharField(blank=True, db_column='rutacertificado', max_length=100, null=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'RECONOCIMIENTOS',
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(db_column='idventagarage', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, db_column='nombreproducto', max_length=100, null=True)),
                ('estadoproducto', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], db_column='estadoproducto', max_length=40, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
                ('valordelbien', models.DecimalField(blank=True, db_column='valordelbien', decimal_places=2, max_digits=5, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(db_column='activarparaqueseveaenfront', default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'VENTAGARAGE',
            },
        ),
    ]
