# Generated by Django 4.2.27 on 2026-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0002_ventagarage_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, db_column='imagen', help_text='Imagen del producto para vista previa en el catálogo', null=True, upload_to='venta_garage/'),
        ),
    ]
