# Generated by Django 4.2.27 on 2026-01-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0003_ventagarage_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventagarage',
            name='imagen',
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen_url',
            field=models.URLField(blank=True, db_column='imagen_url', help_text='URL segura de la imagen del producto almacenada en Azure', null=True),
        ),
    ]
