# Generated by Django 4.2.27 on 2026-01-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0004_remove_ventagarage_imagen_ventagarage_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventagarage',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='rutaimagen',
            field=models.URLField(blank=True, db_column='rutaimagen', help_text='URL segura de la imagen del producto almacenada en Azure', null=True),
        ),
    ]
